package ctrmap.stdlib.gui;

import ctrmap.stdlib.CMStdLibPrefs;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.prefs.Preferences;

public class ComboSelectDialog extends javax.swing.JDialog {

	private Preferences lastOptPrefs = CMStdLibPrefs.node("CTRMapComboSelector");

	private Map<String, Object> userDataMap = new HashMap<>();
	
	private boolean dialogStateCancelled = false;
	private int elementsHash = 131;

	public ComboSelectDialog(java.awt.Frame parent, boolean modal, String title, List<?> options) {
		super(parent, modal);
		cbSelInit(options);
		setLocationRelativeTo(parent);
		if (title != null) {
			setTitle(title);
		}
	}

	public ComboSelectDialog(java.awt.Frame parent, boolean modal, List<?> options) {
		this(parent, modal, null, options);
	}

	private void cbSelInit(List<?> options) {
		initComponents();

		getRootPane().setDefaultButton(btnConfirm);

		for (Object opt : options) {
			elementsHash = 31 * elementsHash + Objects.hashCode(Objects.toString(opt));
		}

		String lastSelectedItem = lastOptPrefs.get(String.valueOf(elementsHash), null);

		selectionBox.removeAllItems();
		
		for (Object opt : options) {
			String val = Objects.toString(opt);
			selectionBox.addItem(val);
			userDataMap.put(val, opt);
		}
		
		if (lastSelectedItem != null && userDataMap.keySet().contains(lastSelectedItem)) {
			selectionBox.setSelectedItem(lastSelectedItem);
		}
		
		setSize(getPreferredSize());
	}

	public Object getSelectedUserObj() {
		if (!dialogStateCancelled) {
			return userDataMap.get(Objects.toString(selectionBox.getSelectedItem()));
		}
		return null;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        selectionBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose an element");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        selectionBox.setMaximumRowCount(20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 116, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirm))
                    .addComponent(selectionBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		dialogStateCancelled = true;
		dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
		lastOptPrefs.put(String.valueOf(elementsHash), Objects.toString(selectionBox.getSelectedItem()));
		dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		btnCancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnCancel;
    protected javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> selectionBox;
    // End of variables declaration//GEN-END:variables
}
