package ctrmap.stdlib.gui.components;

import java.util.ArrayList;
import java.util.List;

public class PlusMinusButtonSet extends javax.swing.JPanel {

	private List<PMButtonListener> listeners = new ArrayList<>();
	
	public PlusMinusButtonSet() {
		initComponents();
	}
	
	public void addListener(PMButtonListener listener){
		listeners.add(listener);
	}

	public void setEnabledDual(boolean enablePlus, boolean enableMinus) {
		btnPlus.setEnabled(enablePlus);
		btnMinus.setEnabled(enableMinus);
	}
	
	@Override
	public void setEnabled(boolean value) {
		super.setEnabled(value);
		setEnabledDual(value, value);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlus = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();

        setOpaque(false);

        btnPlus.setText("+");
        btnPlus.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMinus.setText("-");
        btnMinus.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnPlus)
                .addComponent(btnMinus))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
		for (PMButtonListener l : listeners){
			l.plusClicked();
		}
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        for (PMButtonListener l : listeners){
			l.minusClicked();
		}
    }//GEN-LAST:event_btnMinusActionPerformed

	public static interface PMButtonListener {
		public void plusClicked();
		public void minusClicked();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnPlus;
    // End of variables declaration//GEN-END:variables
}
