package ctrmap.stdlib.gui.components;

import javax.swing.event.ChangeListener;

public class TimePeriodSelector extends javax.swing.JPanel {

	public TimePeriodSelector() {
		initComponents();
	}

	public long getSelectedMillisValue(){
		return getSelectedHourValue() * 60 * 60 * 1000;
	}
	
	public int getSelectedHourValue() {
		int val = ((Number) value.getValue()).intValue();
		switch (timeUnit.getSelectedIndex()) {
			case 0:
				return val;
			case 1:
				return val * 24;
			case 2:
				return val * 168;
		}
		return 0;
	}

	public void setHourValue(int hours) {
		setMillisValue(hours * 60 * 60 * 1000);
	}

	public void setMillisValue(long millis) {
		int hours = Math.round(millis / (60f * 60f * 1000f));
		int days = Math.round(hours / 24f);
		if (hours != 0 && hours % 168 == 0) {
			int weeks = Math.round(days / 7f);
			timeUnit.setSelectedIndex(2);
			value.setValue(weeks);
		} else if (hours != 0 && hours % 7 == 0) {
			timeUnit.setSelectedIndex(1);
			value.setValue(days);
		} else {
			timeUnit.setSelectedIndex(0);
			value.setValue(hours);
		}
	}
	
	public void addChangeListener(ChangeListener cl){
		value.addChangeListener(cl);
	}

	@Override
	public void setEnabled(boolean value) {
		super.setEnabled(value);
		timeUnit.setEnabled(value);
		this.value.setEnabled(value);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        value = new javax.swing.JSpinner();
        timeUnit = new javax.swing.JComboBox<>();

        value.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        timeUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hours", "Days", "Weeks" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(value)
            .addComponent(timeUnit)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> timeUnit;
    private javax.swing.JSpinner value;
    // End of variables declaration//GEN-END:variables
}
