package ctrmap.stdlib.gui.components.combobox;

import java.util.List;
import javax.swing.JComboBox;

public class ACComboBox<T> extends javax.swing.JPanel {

	public ACComboBox() {
		initComponents();
	}
	
	public JComboBox getCB(){
		return cb;
	}
	
	public void setACAlphabeticSort(boolean v){
		cb.setACAlphabeticSort(v);
	}
	
	public boolean getACAlphabeticSort(){
		return cb.getACAlphabeticSort();
	}
	
	public int getSelectedIndex() {
        return cb.getSelectedIndexEx();
    }

    public void setSelectedIndex(int index) {
        cb.setSelectedIndexEx(index);
    }
	
	public void removeAllItems(){
		cb.removeAllItems();
	}
	
	public void addItem(T item){
		cb.addItem(item);
	}
	
	public int getItemCount(){
		return cb.getItemCountEx();
	}

    public Object getSelectedItem() {
        return cb.getSelectedItem();
    }

    public void setSelectedItem(T item) {
        cb.setSelectedItem(item);
    }

    public void setMaximumRowCount(int rowCount) {
        cb.setMaximumRowCount(rowCount);
    }
	
	public void loadValues(T... values){
		cb.loadValues(values);
	}
	
	public void loadValues(List<T> values){
		cb.loadValues(values);
	}
	
	public void addListener(ComboBoxExInternal.ComboBoxListener listener){
		cb.addListener(listener);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb = new ctrmap.stdlib.gui.components.combobox.ComboBoxExInternal<>();

        cb.setMaximumRowCount(25);
        cb.setACAlphabeticSort(true);
        cb.setACMode(ctrmap.stdlib.gui.components.combobox.ComboBoxExInternal.ACMode.CONTAINS);
        cb.setAllowAC(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ctrmap.stdlib.gui.components.combobox.ComboBoxExInternal<T> cb;
    // End of variables declaration//GEN-END:variables
}
