package xstandard.gui;

import xstandard.XStandardPrefs;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Function;
import java.util.prefs.Preferences;

public class ComboSelectDialog<T> extends javax.swing.JDialog {

	private Preferences lastOptPrefs = XStandardPrefs.node("ComboSelector");
	
	private boolean dialogStateCancelled = false;
	private int elementsHash = 131;
	
	private final Function<T, String> toStringFunc;
	
	public ComboSelectDialog(java.awt.Frame parent, boolean modal, String title, List<T> options) {
		this(parent, modal, title, options, new Function<T, String>() {
			@Override
			public String apply(T t) {
				return Objects.toString(t);
			}
		});
	}
	
	public ComboSelectDialog(java.awt.Frame parent, boolean modal, String title, List<T> options, Function<T, String> stringCvtr) {
		super(parent, modal);
		toStringFunc = stringCvtr;
		cbSelInit(options);
		setLocationRelativeTo(parent);
		if (title != null) {
			setTitle(title);
		}
	}

	public ComboSelectDialog(java.awt.Frame parent, boolean modal, List<T> options) {
		this(parent, modal, null, options);
	}

	private void cbSelInit(List<T> options) {
		initComponents();

		getRootPane().setDefaultButton(btnConfirm);

		for (Object opt : options) {
			elementsHash = 31 * elementsHash + Objects.hashCode(Objects.toString(opt));
		}

		String lastSelectedItem = lastOptPrefs.get(String.valueOf(elementsHash), null);

		selectionBox.removeAllItems();
		
		Map<String, Object> map = new HashMap<>();
		for (T opt : options) {
			UserObjWrapper<T> w = new UserObjWrapper<>(opt, toStringFunc);
			map.put(w.toString(), opt);
			selectionBox.addItem(w);
		}
		
		if (lastSelectedItem != null && map.containsKey(lastSelectedItem)) {
			selectionBox.setSelectedItem(map.get(lastSelectedItem));
		}
		
		setSize(getPreferredSize());
	}

	public T getSelectedUserObj() {
		if (!dialogStateCancelled) {
			Object item = selectionBox.getSelectedItem();
			if (item != null && item instanceof UserObjWrapper) {
				return ((UserObjWrapper<T>) item).obj;
			}
		}
		return null;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        selectionBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose an element");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        selectionBox.setMaximumRowCount(20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 116, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirm))
                    .addComponent(selectionBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		dialogStateCancelled = true;
		dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
		lastOptPrefs.put(String.valueOf(elementsHash), Objects.toString(selectionBox.getSelectedItem()));
		dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		btnCancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnCancel;
    protected javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<UserObjWrapper> selectionBox;
    // End of variables declaration//GEN-END:variables

	private static class UserObjWrapper<T> {
		
		private final T obj;
		private final Function<T, String> toStringFunc;
		
		public UserObjWrapper(T obj, Function<T, String> toStringFunc) {
			this.obj = obj;
			this.toStringFunc = toStringFunc;
		}
		
		@Override
		public String toString() {
			return toStringFunc.apply(obj);
		}
	}
}
